AWSTemplateFormatVersion: '2010-09-09'
Description: Criação de uma instância EC2

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      KeyName: my-key
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: EC2Instance

Outputs:
  InstanceId:
    Value: !Ref MyEC2Instance
